### ISSUE TITLE
Analysis.ipynb cv2.imread BGR2RGB conversion

### ISSUE THREAD

**Issue by hyadamhuang** [msminhas93/DeepLabv3FineTuning#16]
Analysis.ipynb, in [6]
img = cv2.imread(f'./CrackForest/Images/{ino:03d}.jpg').transpose(2,0,1).reshape(1,3,320,480)
will convert RGB image incorrectly. 
(cv2 and PIL Image read RGB image format differently)
(need to use cv2.cvtColor for fixing cv2's BGR into RGB)
img = cv2.imread(f'./CrackForest/Images/{ino:03d}.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).transpose(2,0,1).reshape(1,3,320,480)

**Comment by msminhas93** [comment]
Thank you Huang for pointing this out! Since the images are grayscale R=G=B when we load it using OpenCV. But for colour images you are absolutely right. I'll update the code to add this. :D
<img width="519" alt="hAAFVATywx" src="https://user-images.githubusercontent.com/6465972/110880558-d2f21b80-82ac-11eb-8a34-7fc064eac239.png">
